# Each entry: name (required), category (required), slug/board (optional known hints).
# Categories: quant_fund, trading_shop, crypto_trading, bank, asset_manager, vc, fintech, tech, crypto
#
# "slug" and "board" are optional hints for discovery — saves time when we already know the ATS.
# Companies without a public ATS (e.g. Renaissance, DE Shaw) will be flagged as not found.

COMPANIES = [
    # ── Quant / Systematic Hedge Funds ────────────────────────────────────────
    {"name": "Two Sigma", "category": "quant_fund"},
    {"name": "DE Shaw", "category": "quant_fund"},
    {"name": "Citadel", "category": "quant_fund"},
    {"name": "AQR Capital Management", "category": "quant_fund"},
    {"name": "Point72", "category": "quant_fund"},
    {"name": "Millennium Management", "category": "quant_fund"},
    {"name": "Bridgewater Associates", "category": "quant_fund"},
    {"name": "Man AHL", "category": "quant_fund"},
    {"name": "Winton Group", "category": "quant_fund"},
    {"name": "WorldQuant", "category": "quant_fund"},
    {"name": "PDT Partners", "category": "quant_fund"},
    {"name": "Qube Research & Technologies", "category": "quant_fund"},
    {"name": "Squarepoint Capital", "category": "quant_fund"},
    {"name": "Balyasny Asset Management", "category": "quant_fund"},
    {"name": "Marshall Wace", "category": "quant_fund"},
    {"name": "Schonfeld Strategic Advisors", "category": "quant_fund"},
    {"name": "G-Research", "category": "quant_fund"},
    {"name": "ExodusPoint Capital", "category": "quant_fund"},
    {"name": "Verition Fund Management", "category": "quant_fund"},
    {"name": "Symmetry Investments", "category": "quant_fund"},
    {"name": "Systematica Investments", "category": "quant_fund"},
    {"name": "Alphadyne Asset Management", "category": "quant_fund"},
    {"name": "Capula Investment Management", "category": "quant_fund"},
    {"name": "Numerai", "category": "quant_fund"},

    # ── Traditional / Multi-Strategy Hedge Funds ───────────────────────────
    {"name": "Elliott Management", "category": "quant_fund"},
    {"name": "Pershing Square Capital", "category": "quant_fund"},
    {"name": "Third Point", "category": "quant_fund"},
    {"name": "Davidson Kempner", "category": "quant_fund"},
    {"name": "Farallon Capital", "category": "quant_fund"},
    {"name": "Magnetar Capital", "category": "quant_fund"},
    {"name": "Graham Capital Management", "category": "quant_fund"},
    {"name": "Brevan Howard", "category": "quant_fund"},
    {"name": "Coatue Management", "category": "quant_fund"},
    {"name": "Tiger Global Management", "category": "quant_fund"},
    {"name": "Highbridge Capital Management", "category": "quant_fund"},
    {"name": "Taconic Capital", "category": "quant_fund"},
    {"name": "Moore Capital Management", "category": "quant_fund"},
    {"name": "Lone Pine Capital", "category": "quant_fund"},
    {"name": "Viking Global Investors", "category": "quant_fund"},
    {"name": "Citadel Wellington", "category": "quant_fund"},

    # ── Trading Shops / Market Makers ──────────────────────────────────────
    {"name": "Jane Street", "category": "trading_shop"},
    {"name": "Jump Trading", "category": "trading_shop"},
    {"name": "Virtu Financial", "category": "trading_shop"},
    {"name": "Hudson River Trading", "category": "trading_shop"},
    {"name": "Tower Research Capital", "category": "trading_shop"},
    {"name": "Optiver", "category": "trading_shop"},
    {"name": "IMC Trading", "category": "trading_shop"},
    {"name": "Susquehanna International Group", "category": "trading_shop"},
    {"name": "DRW", "category": "trading_shop"},
    {"name": "Flow Traders", "category": "trading_shop"},
    {"name": "Wolverine Trading", "category": "trading_shop"},
    {"name": "Belvedere Trading", "category": "trading_shop"},
    {"name": "XTX Markets", "category": "trading_shop"},
    {"name": "Headlands Technologies", "category": "trading_shop"},
    {"name": "Citadel Securities", "category": "trading_shop"},
    {"name": "Five Rings Capital", "category": "trading_shop"},
    {"name": "Akuna Capital", "category": "trading_shop"},
    {"name": "Chicago Trading Company", "category": "trading_shop"},
    {"name": "Old Mission Capital", "category": "trading_shop"},
    {"name": "TransMarket Group", "category": "trading_shop"},
    {"name": "Maven Securities", "category": "trading_shop"},

    # ── Family Offices ──────────────────────────────────────────────────────
    {"name": "Soros Fund Management", "category": "quant_fund"},
    {"name": "Duquesne Family Office", "category": "quant_fund"},
    {"name": "Emerson Collective", "category": "quant_fund"},

    # ── Investment Banks ────────────────────────────────────────────────────
    {"name": "Goldman Sachs", "category": "bank"},
    {"name": "JPMorgan", "category": "bank"},
    {"name": "Morgan Stanley", "category": "bank"},
    {"name": "Citigroup", "category": "bank"},
    {"name": "Bank of America", "category": "bank"},
    {"name": "Barclays", "category": "bank"},
    {"name": "Deutsche Bank", "category": "bank"},
    {"name": "UBS", "category": "bank"},
    {"name": "HSBC", "category": "bank"},
    {"name": "Nomura", "category": "bank"},
    {"name": "Jefferies", "category": "bank"},
    {"name": "Lazard", "category": "bank"},
    {"name": "Evercore", "category": "bank"},
    {"name": "Wells Fargo", "category": "bank"},
    {"name": "BNP Paribas", "category": "bank"},
    {"name": "Societe Generale", "category": "bank"},
    {"name": "Credit Agricole", "category": "bank"},

    # ── Asset Managers ──────────────────────────────────────────────────────
    {"name": "BlackRock", "category": "asset_manager"},
    {"name": "Vanguard", "category": "asset_manager"},
    {"name": "Fidelity Investments", "category": "asset_manager"},
    {"name": "PIMCO", "category": "asset_manager"},
    {"name": "State Street Global Advisors", "category": "asset_manager"},
    {"name": "Wellington Management", "category": "asset_manager"},
    {"name": "Dimensional Fund Advisors", "category": "asset_manager"},
    {"name": "Nuveen", "category": "asset_manager"},
    {"name": "T. Rowe Price", "category": "asset_manager"},
    {"name": "Northern Trust", "category": "asset_manager"},
    {"name": "Franklin Templeton", "category": "asset_manager"},
    {"name": "Invesco", "category": "asset_manager"},
    {"name": "AllianceBernstein", "category": "asset_manager"},
    {"name": "Neuberger Berman", "category": "asset_manager"},
    {"name": "Apollo Global Management", "category": "asset_manager"},
    {"name": "KKR", "category": "asset_manager"},
    {"name": "Carlyle Group", "category": "asset_manager"},
    {"name": "Blackstone", "category": "asset_manager"},
    {"name": "Ares Management", "category": "asset_manager"},
    {"name": "Warburg Pincus", "category": "asset_manager"},
    {"name": "General Atlantic", "category": "asset_manager"},
    {"name": "Bain Capital", "category": "asset_manager"},
    {"name": "TPG", "category": "asset_manager"},
    {"name": "PGIM", "category": "asset_manager"},
    {"name": "Putnam Investments", "category": "asset_manager"},
    {"name": "Lord Abbett", "category": "asset_manager"},
    {"name": "Nuveen Investments", "category": "asset_manager"},

    # ── VC Firms ────────────────────────────────────────────────────────────
    {"name": "Andreessen Horowitz", "category": "vc"},
    {"name": "Sequoia Capital", "category": "vc"},
    {"name": "General Catalyst", "category": "vc"},
    {"name": "Lightspeed Venture Partners", "category": "vc"},
    {"name": "Benchmark", "category": "vc"},
    {"name": "Kleiner Perkins", "category": "vc"},
    {"name": "Accel", "category": "vc"},
    {"name": "Bessemer Venture Partners", "category": "vc"},
    {"name": "GV", "category": "vc"},
    {"name": "IVP", "category": "vc"},
    {"name": "Founders Fund", "category": "vc"},
    {"name": "Greylock", "category": "vc"},
    {"name": "Index Ventures", "category": "vc"},
    {"name": "Battery Ventures", "category": "vc"},
    {"name": "NEA", "category": "vc"},
    {"name": "Insight Partners", "category": "vc"},
    {"name": "Union Square Ventures", "category": "vc"},
    {"name": "Paradigm", "category": "vc"},
    {"name": "Pantera Capital", "category": "vc"},
    {"name": "Multicoin Capital", "category": "vc"},
    {"name": "Craft Ventures", "category": "vc"},
    {"name": "Coatue Ventures", "category": "vc"},

    # ── Crypto / Digital Assets ─────────────────────────────────────────────
    {"name": "Coinbase", "category": "crypto"},
    {"name": "Gemini", "category": "crypto"},
    {"name": "Kraken", "category": "crypto"},
    {"name": "Galaxy Digital", "category": "crypto"},
    {"name": "Grayscale Investments", "category": "crypto"},
    {"name": "Wintermute Trading", "category": "crypto_trading"},
    {"name": "GSR Markets", "category": "crypto_trading"},
    {"name": "Cumberland", "category": "crypto_trading"},
    {"name": "Anchorage Digital", "category": "crypto"},
    {"name": "BitGo", "category": "crypto"},
    {"name": "Fireblocks", "category": "crypto"},
    {"name": "Chainalysis", "category": "crypto"},
    {"name": "Alchemy", "category": "crypto"},
    {"name": "Deribit", "category": "crypto_trading"},
    {"name": "B2C2", "category": "crypto_trading"},

    # ── Quant-Adjacent Tech / Fintech / Data ────────────────────────────────
    {"name": "Palantir", "category": "tech"},
    {"name": "Databricks", "category": "tech"},
    {"name": "Scale AI", "category": "tech"},
    {"name": "Stripe", "category": "fintech"},
    {"name": "Plaid", "category": "fintech"},
    {"name": "Robinhood", "category": "fintech"},
    {"name": "Bloomberg", "category": "tech"},
    {"name": "FactSet", "category": "tech"},
    {"name": "S&P Global", "category": "tech"},
    {"name": "MSCI", "category": "tech"},
    {"name": "Kensho", "category": "tech"},
    {"name": "Ramp", "category": "fintech"},
    {"name": "Brex", "category": "fintech"},
    {"name": "Affirm", "category": "fintech"},
    {"name": "SoFi", "category": "fintech"},
    {"name": "Chime", "category": "fintech"},
    {"name": "Marqeta", "category": "fintech"},
    {"name": "OpenAI", "category": "tech"},
    {"name": "Anthropic", "category": "tech"},
    {"name": "xAI", "category": "tech"},
    {"name": "Waymo", "category": "tech"},
    {"name": "Refinitiv", "category": "tech"},
]
